### ISSUE TITLE
strict token checking

### ISSUE THREAD

**Issue by shrikantr-iprogrammer** [sqreen/vue-authentication-example#2]
Even if I delete the token from local storage and click on any link I reach to that page. Ideally it should redirect me to login page. But yes when I refresh the page it takes me to the login page.

**Comment by vouill** [comment]
You are right ! 
When the user click an authenticated page, it should be redirected to /login. Why ? because of the axios interecptors for unauthenticated calls. 
However this demo doesnt use any apis and mocks the api calls. The mocked api calls here do no handle this case. If you want you can try yourself and make a PR, i d be happy to review it :)
